[build]
  command = "npm run build"

# Config for the Netlify Build Plugin: netlify-plugin-add-instagram
[[plugins]]
  package = "../netlify-plugin-add-instagram"

  [plugins.inputs]

    # Where to put the image files
    imageFolder = "src/images/instagram"

    # Also stash data about the images in a json file
    dataFile = "src/_data/instagram.json"

    # how many seconds should we cache the instagram feed for?
    ttl = 60
